/**
 * Inventory Sync Worker
 *
 * Runs daily to sync inventory across all platforms
 * and check for reorder points.
 */

import prisma from '../utils/prisma.js';
import ShopifyService from '../services/ShopifyService.js';
import logger from '../utils/logger.js';

export async function processInventorySync(data) {
  const { platformId } = data;

  logger.info('Starting inventory sync', { platformId });

  try {
    let platforms;

    if (platformId) {
      // Sync specific platform
      platforms = await prisma.platform.findMany({
        where: {
          id: platformId,
          syncEnabled: true,
        },
        include: { user: true },
      });
    } else {
      // Sync all platforms
      platforms = await prisma.platform.findMany({
        where: {
          status: 'CONNECTED',
          syncEnabled: true,
        },
        include: { user: true },
      });
    }

    logger.info(`Syncing inventory for ${platforms.length} platforms`);

    const results = [];

    for (const platform of platforms) {
      try {
        let syncResult;

        switch (platform.type) {
          case 'SHOPIFY':
            syncResult = await ShopifyService.syncProducts(platform.id);
            break;

          // TODO: Add other platforms
          case 'ETSY':
          case 'EBAY':
          case 'AMAZON':
            logger.info(`Sync for ${platform.type} not yet implemented`);
            continue;

          default:
            logger.warn(`Unknown platform type: ${platform.type}`);
            continue;
        }

        results.push({
          platformId: platform.id,
          platformType: platform.type,
          ...syncResult,
        });

        // Check for low inventory after sync
        const lowStockItems = await prisma.inventoryItem.findMany({
          where: {
            platformId: platform.id,
            available: {
              lte: prisma.inventoryItem.fields.reorderPoint,
            },
          },
          include: {
            product: true,
          },
        });

        // Create alerts for low stock
        for (const item of lowStockItems) {
          await prisma.alert.create({
            data: {
              userId: platform.userId,
              type: 'INVENTORY_LOW',
              severity: item.available === 0 ? 'CRITICAL' : 'WARNING',
              title: `Low stock: ${item.product.name}`,
              message: `Only ${item.available} units left (reorder point: ${item.reorderPoint})`,
              entityType: 'InventoryItem',
              entityId: item.id,
              actionRequired: true,
              actionUrl: '/inventory',
              actionLabel: 'View Inventory',
            },
          });

          // Auto-generate purchase order if enabled
          if (item.supplierName && item.reorderQuantity) {
            const existingPO = await prisma.purchaseOrder.findFirst({
              where: {
                productId: item.productId,
                status: { in: ['DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'ORDERED'] },
              },
            });

            if (!existingPO) {
              await prisma.purchaseOrder.create({
                data: {
                  productId: item.productId,
                  poNumber: `PO-${Date.now()}`,
                  status: 'DRAFT',
                  supplierName: item.supplierName,
                  quantity: item.reorderQuantity,
                  unitCost: item.unitCost || 0,
                  totalCost: (item.unitCost || 0) * item.reorderQuantity,
                  autoGenerated: true,
                  triggerReason: `Low stock alert (${item.available} units remaining)`,
                },
              });

              logger.info(`Auto-generated PO for ${item.product.name}`);
            }
          }
        }

        if (lowStockItems.length > 0) {
          logger.warn(`Found ${lowStockItems.length} low stock items for platform ${platform.id}`);
        }
      } catch (error) {
        logger.error(`Failed to sync platform ${platform.id}:`, error);
      }
    }

    const summary = {
      platformsSynced: results.length,
      totalProducts: results.reduce((sum, r) => sum + (r.syncedCount || 0), 0),
      totalCreated: results.reduce((sum, r) => sum + (r.createdCount || 0), 0),
      totalUpdated: results.reduce((sum, r) => sum + (r.updatedCount || 0), 0),
    };

    logger.info('Inventory sync complete', summary);

    return summary;
  } catch (error) {
    logger.error('Inventory sync worker failed:', error);
    throw error;
  }
}
