import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Alert, AlertDescription } from '@/components/ui/alert';
import {
    Code,
    FileJson,
    Sparkles,
    AlertCircle,
    CheckCircle
} from 'lucide-react';

export default function MockDataConfigurator({ automation, onDataChange }) {
    const [mode, setMode] = useState('auto'); // auto, manual
    const [jsonData, setJsonData] = useState('');
    const [jsonValid, setJsonValid] = useState(true);
    const [autoGeneratedData, setAutoGeneratedData] = useState(null);

    useEffect(() => {
        // Auto-generate mock data based on trigger type
        const generated = generateMockData(automation);
        setAutoGeneratedData(generated);
        if (mode === 'auto') {
            onDataChange(generated);
        }
    }, [automation, mode]);

    const generateMockData = (automation) => {
        if (!automation || !automation.trigger_id) {
            return { timestamp: new Date().toISOString() };
        }

        // Get trigger type from automation (would normally fetch from trigger)
        const triggerType = automation.trigger_type || 'schedule';

        const mockData = {
            timestamp: new Date().toISOString(),
            automation_id: automation.id,
            automation_name: automation.name
        };

        switch (triggerType) {
            case 'inventory_low':
                mockData.trigger_data = {
                    product_id: 'mock_prod_123',
                    product_name: 'Test Product',
                    current_stock: 5,
                    threshold: 10,
                    sku: 'TEST-SKU-001'
                };
                break;

            case 'order_placed':
                mockData.trigger_data = {
                    order_id: 'mock_order_456',
                    customer_name: 'Test Customer',
                    customer_email: 'test@example.com',
                    total_amount: 99.99,
                    items_count: 3,
                    platform: 'shopify'
                };
                break;

            case 'schedule':
                mockData.trigger_data = {
                    scheduled_time: new Date().toISOString(),
                    frequency: 'daily',
                    execution_count: 1
                };
                break;

            case 'price_change':
                mockData.trigger_data = {
                    product_id: 'mock_prod_789',
                    product_name: 'Test Product',
                    old_price: 49.99,
                    new_price: 39.99,
                    change_percentage: -20
                };
                break;

            case 'new_review':
                mockData.trigger_data = {
                    product_id: 'mock_prod_321',
                    rating: 4,
                    review_text: 'Great product, very satisfied!',
                    customer_name: 'Happy Customer',
                    verified_purchase: true
                };
                break;

            case 'ad_spend_threshold':
                mockData.trigger_data = {
                    campaign_id: 'mock_campaign_999',
                    current_spend: 150.00,
                    threshold: 100.00,
                    platform: 'facebook'
                };
                break;

            case 'revenue_milestone':
                mockData.trigger_data = {
                    current_revenue: 1250.00,
                    milestone: 1000.00,
                    period: 'daily',
                    orders_count: 42
                };
                break;

            default:
                mockData.trigger_data = {
                    event_type: triggerType,
                    data: {}
                };
        }

        return mockData;
    };

    const handleJsonChange = (value) => {
        setJsonData(value);
        try {
            const parsed = JSON.parse(value);
            setJsonValid(true);
            onDataChange(parsed);
        } catch (error) {
            setJsonValid(false);
        }
    };

    const handleModeChange = (newMode) => {
        setMode(newMode);
        if (newMode === 'auto') {
            onDataChange(autoGeneratedData);
        } else if (newMode === 'manual') {
            setJsonData(JSON.stringify(autoGeneratedData, null, 2));
        }
    };

    return (
        <Card>
            <CardHeader>
                <CardTitle className="flex items-center gap-2">
                    <FileJson className="w-5 h-5 text-indigo-600" />
                    Mock Trigger Data
                </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
                <Tabs value={mode} onValueChange={handleModeChange}>
                    <TabsList className="grid w-full grid-cols-2">
                        <TabsTrigger value="auto">
                            <Sparkles className="w-4 h-4 mr-2" />
                            Auto-Generated
                        </TabsTrigger>
                        <TabsTrigger value="manual">
                            <Code className="w-4 h-4 mr-2" />
                            Manual JSON
                        </TabsTrigger>
                    </TabsList>

                    <TabsContent value="auto" className="space-y-4">
                        <Alert>
                            <AlertDescription>
                                Mock data has been automatically generated based on your trigger type.
                                This data will be used to simulate the trigger event.
                            </AlertDescription>
                        </Alert>

                        <div className="bg-slate-900 text-slate-100 rounded-lg p-4 text-xs font-mono overflow-x-auto">
                            <pre>{JSON.stringify(autoGeneratedData, null, 2)}</pre>
                        </div>

                        <div className="flex items-center gap-2 text-sm text-slate-600">
                            <CheckCircle className="w-4 h-4 text-green-600" />
                            <span>Ready to test with auto-generated data</span>
                        </div>
                    </TabsContent>

                    <TabsContent value="manual" className="space-y-4">
                        <Alert>
                            <AlertDescription>
                                Provide custom JSON data to test specific scenarios or edge cases.
                            </AlertDescription>
                        </Alert>

                        <div>
                            <Label>Custom JSON Data</Label>
                            <Textarea
                                value={jsonData}
                                onChange={(e) => handleJsonChange(e.target.value)}
                                placeholder="Enter JSON data..."
                                className="font-mono text-xs h-64 mt-2"
                            />
                        </div>

                        <div className="flex items-center gap-2 text-sm">
                            {jsonValid ? (
                                <>
                                    <CheckCircle className="w-4 h-4 text-green-600" />
                                    <span className="text-green-600">Valid JSON</span>
                                </>
                            ) : (
                                <>
                                    <AlertCircle className="w-4 h-4 text-red-600" />
                                    <span className="text-red-600">Invalid JSON format</span>
                                </>
                            )}
                        </div>
                    </TabsContent>
                </Tabs>
            </CardContent>
        </Card>
    );
}